# -*- coding: utf-8 -*-
"""6.dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zc5GQ97jXQevnp7_HGSTGfqqLpT-rMPA
"""

#Q1: Create a dictionary with 3 fruits and their prices. Print the price of one fruit.

fruits = {
"mango": 200,
"banana": 150,
"apple": 250
}
print(fruits)

#Make a dictionary of 3 students with their names as keys and marks as values. Print all
students = {
    "ali": 900,
    "ahmed": 920,
    "wania": 944
}

print(students)

#Create a dictionary of 5 countries and their capitals. Ask the user to input a country and print
countries = {
     "Pakistan": "Islamabad",
     "dubai": "abudhabi",
     "USA": "Washington",
     "FRANCE": "paris",
     "GERMONEY": "berlin"
 }
print(countries)

#Create a dictionary with numbers as keys and their squares as values (for numbers 1 to 5)
numbers = {
    1: 1,
    2: 4,
    3: 9,
    4: 16,
    5: 25
}
print(numbers)

#Create a dictionary of a person with keys: name, age, city.
person = {
    "name": "hamna",
    "age": 21,
    "city": "bahawalpur"
}
print(person)

person["age"] = 22
print(person)

#Make a nested dictionary:
students = {
    "ali": {"age": 23, "grade":"B"},
    "hamna": {"age": 21, "grade":"B"}
}
print(students)


#Create a dictionary and remove one key-value pair using pop().
# Create dictionary
car = {
    "brand": "Toyota",
    "model": "Corolla",
    "year": 2020
}

print("Before:", car)

# Remove a key-value pair using pop()
car.pop("model")

print("After:", car)