# -*- coding: utf-8 -*-
"""7.List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJ_a23wtZQy56nImFmnwt33CadVB0UkA
"""

#Create a list of 7 numbers. Print only the even numbers from the list.

numbers = [10, 15, 22, 33, 40, 55, 60]

print("even numbers are:")
for num in numbers:
  if num % 2 == 0:
    print(num)

#Create a list of 5 student names. Ask the user to input a name, and check if it exists in the
students = ["hamna", "fatima", "meryam", "ahmed", "ali"]
student = input("enter a student name: ")
if student in students:
  print("found")
else:
  print("not found")

#Create a list of 6 numbers. Print the maximum and minimum numbers

numbers = [10, 15, 22, 33, 55, 60]
print("maximum number is:" "60")

print("minumum number is:" "10")

#Create a list of 6 numbers. Print the maximum and minimum numbers
numbers = [10, 15, 22, 33, 55, 60]

maximum = numbers[0]
minimum = numbers[0]

for num in numbers:
  if num > maximum:
    maximum = num
    if num < minimum:
      minimum = num
print("maximum num is:", maximum)
print("minimum num is:", minimum)

from ast import Mult
#Create a list [2, 4, 6, 8, 10]. Multiply each number by 3

numbers = [2, 4, 6, 8, 10]
Mult

#Create a list [2, 4, 6, 8, 10]. Multiply each number by 3 and store the results in a new


numbers = [2, 4, 6, 8, 10]
newlist = []
for number in numbers:
 newlist.append(number * 3)

print("numbers:", numbers)
print("newlist:", newlist)

