# -*- coding: utf-8 -*-
"""FIRST ASSIGMENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxb5ceyAnse1njtcGG259wZz0zvj1WuU
"""

birth_year = int(input("enter your birth year"))

current_year =  int(input("enter current year"))
age =  current_year - birth_year
print("you are " , age , "years old ")

principal_amount = int(input("enter your principal amount"))
rate_of_interest = int(input("enter your rate of interest"))
time = int(input("enter time"))

interest = principal_amount*rate_of_interest*time/100
print(interest)

length = int(input("entr length"))
width = int(input("enter width"))

area = length*width

print(area)

radius = int(input("Enter the radius of the circle"))
pi = 3.14159
area = pi*radius*radius
circumference = 2*pi*radius

print("Area of Circle:", area)
print("Circumference of Circle:", circumference)

C = int(input("enetr C"))
F = (C*9/5)+32
print("temperature in faranhite:", F)

first_num = int(input("enter num"))
sec_num = int(input("enter num"))
third_num = int(input("enter num"))

average = first_num+sec_num+third_num

print("sum of these:", average)